we keep the if in a function and we r using it

diff --git a/frontend-sh b/frontend-sh
--- a/frontend-sh
+++ b/frontend-sh
@@ -1,38 +1,35 @@
 source common.sh
 print_head "installing nginx"
 yum install nginx -y &>>${log_file}
- if [ $? -eq 0 ]; then
-   echo SUCCESS
-   else
-   echo FAILURE
-   fi
+status_check $?
 
 
 print_head "removing old content"
 rm -rf /usr/share/nginx/html/*  &>>${log_file}
-echo $?
+status_check $?
 print_head "downloading frontend content"
 
 curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip &>>${log_file}
-echo $?
+status_check $?
 print_head "extracting downloaded frontend"
 cd /usr/share/nginx/html
-echo $?
+status_check $?
 
 unzip /tmp/frontend.zip &>>${log_file}
-echo $?
+status_check $?
 print_head "copying nginx config for roboshop"
 
 cp ${code_dir}/configs/nginx-roboshop.conf /etc/nginx/default.d/roboshop.conf &>>${log_file}
-echo $?
+status_check $?
 print_head "enabling nginx"
 systemctl enable nginx &>>${log_file}
-echo $?
+status_check $?
 print_head "starting nginx"
 systemctl restart nginx &>>${log_file}
-echo $?
+status_check $?
 
-
+# if any command is errored or failed,we need to stop the script
+# status of command need to b printed
 
 
 
